**Numpy**

~Numpy is a Linear Algebra Library in python and it is the holy grail and Main building bock of Data Science.
~Numpy stands for Numerical Python which is used to perform Numerical Calculations
~Numpy is used to Handle arrays and Matrices

**What is Numpy?**
~Numpy is a python Libraray/Package that used to work with arrays
~It is also adtastructure Used to Store multiple values.
~Numpy provides efficient Way of storing and manupulating data.
~It offers wide variety of Mathematical functions which helps in solving complex math problems of linear Algebra,fourier transform and vectors

**Why Numpy?**
~Faster and More Compact than Lists.
~consumes less memory.
~data typr can be specified.
~high level mathematical Fuctions can be used.
~used to solve problems related to linear algebra,fourier transform,vectors etc

**What is Array?**
Numpy arrays commonly used data structures in python that store data as a grid,or  a matrix and easy to acess

In [2]:
#importing numpy library using import statement
import numpy as np

**Numpy Array Creation**

In [3]:
#creating empty array
arr=np.array([])
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[]


In [5]:
#create numpy array to store values such as 9,8,7,6,5
arr1=np.array([6,7,8,9,5,6])
print(arr1)
print(type(arr1))

[6 7 8 9 5 6]
<class 'numpy.ndarray'>


In [6]:
#create a  array to store string varaibles
#paranthesis() also used 
Colors=np.array(["Blue","Green","Red","Orange","white"])
print(Colors)
print(type(Colors))

['Blue' 'Green' 'Red' 'Orange' 'white']
<class 'numpy.ndarray'>


In [8]:
#how to create an array using list
#you can create a array using[]list,and using()tuple also
List=[30,38,27,43,16,35,27,45]
arr=np.array([List])
print(arr)
print(type(arr))


[[30 38 27 43 16 35 27 45]]
<class 'numpy.ndarray'>


In [12]:
#how to create an array using tuple
tuple=(10,20,30,50,23,45)
arr1=np.array(tuple)
print(arr1)
print(type(arr1))
#array can only created using list and tuple but not using sets and dictionaries

[10 20 30 50 23 45]
<class 'numpy.ndarray'>


**1-D Array**

In [20]:
arr=np.array([1,2,3,4,5,6,7,8])
print(arr)
#ndim is used to find dimension of array
print("dimension of array is ",arr.ndim)
#size is used to find number of elements of array
print("Number of elements is",arr.size)
#dtype is used to find datatype of elements array
print("datatype of an array element is",arr.dtype)

[1 2 3 4 5 6 7 8]
dimension of array is  1
Number of elements is 8
datatype of an array element is int32


**2-D Array -matrices**

In [29]:
arr_2d=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr_2d)
print("dimension of array is ",arr_2d.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
dimension of array is  2


In [35]:
arr2d=np.array([[4,5,6,7],[8,9,1,2],[3,2,4,5],[9,2,1,4]])
print(arr2d)
print("dimension of array is ",arr2d.ndim)
print("data type of elements in array is",arr.dtype)
print("Number of elements is",arr2d.size)
#shape used to find the order of matrices (no of rows and columns)
print("order of the matrics is",arr2d.shape)

[[4 5 6 7]
 [8 9 1 2]
 [3 2 4 5]
 [9 2 1 4]]
dimension of array is  2
data type of elements in array is int32
Number of elements is 16
order of the matrics is (4, 4)


**3-D Array**

In [41]:
arr_3d=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr_3d)
print("order of matrics is",arr_3d.shape)
print("dimension of array is ",arr_3d.ndim)


[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
order of matrics is (1, 3, 3)
dimension of array is  3


In [45]:
#assignment
#4-D array,5D,6D
arr_4d=np.array([[[[1,2,3],[4,5,6],[7,8,9]]]])
print(arr_4d)

[[[[1 2 3]
   [4 5 6]
   [7 8 9]]]]


**Built-in Functions To Generate Numpy Arrays**

In [46]:
#generate values from 0 to 40
#arange :function used to generate evenly spaced values within given interval
#NOTE: end value is not included


In [50]:
arr1=np.arange(15) #end value not included
arr2=np.arange(31)
print(arr1)
print(arr2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]


In [51]:
#generate values from 101 to 150
np.arange(101,151)

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
       114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126,
       127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
       140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])

In [52]:
#generate values from 400 to 480
np.arange(400,481)

array([400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412,
       413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425,
       426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438,
       439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451,
       452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464,
       465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477,
       478, 479, 480])

In [55]:
#generate first 10 even numbers
np.arange(2,21,2) #start,stop,step

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [59]:
#generate an array which includes 10 multiples of 5
np.arange(5,51,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [60]:
#generate 10 multiples of 8
np.arange(8,81,8)

array([ 8, 16, 24, 32, 40, 48, 56, 64, 72, 80])

**ONES**

In [61]:
#ones:returns an array with all ones
#return 1-D array with 3 elements as 1
np.ones(3)

array([1., 1., 1.])

In [62]:
#return 1-D array 10 elemnts as 1
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [63]:
#create unit matrix of order(2,2)
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [65]:
#create unit matrix of order(5,3)
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

**Zeros**

In [2]:
#create 1D array with 5 elements are 0
import numpy as np
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
#create a 2D array of order(3,3)
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

**eye--Identity matrix**

In [6]:
#create a (2,2) identity matrix
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [7]:
#craete a (3,3) identity matrix
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
#create a (4,3) identity matrix
np.eye(4,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

**Full- it is used to generate array with same elements**

In [10]:
#create an (2,2)array with all elements as 10
np.full((2,2),10)

array([[10, 10],
       [10, 10]])

In [11]:
#create (4,3) matrix with all elements as 20
np.full((4,3),20)

array([[20, 20, 20],
       [20, 20, 20],
       [20, 20, 20],
       [20, 20, 20]])

**LINSPACE : it is used to generate linearly spaced values**

In [12]:
#generate a linearly spaced values between 1 to 5
np.linspace(1,5)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [14]:
#generate 10 equally spaced values between 1 to 100
#retstep shows the difference value
np.linspace(1,100,num=10,retstep=True)

(array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.]), 11.0)

In [17]:
#generate a 10 numbers between 1 to 1000 and find the difference 
np.linspace(1,1000,num=10,retstep=True)

(array([   1.,  112.,  223.,  334.,  445.,  556.,  667.,  778.,  889.,
        1000.]),
 111.0)

**Random**

**randint**

In [23]:
#create an array which includes 10 random integers between 1 to 100
#Random used to generate random numbers
#randint --it is used to generate a random integers for given interval
np.random.randint(1,100,10)

array([ 7, 17, 90, 64, 54,  1, 17, 44, 93, 38])

In [25]:
#generate an array which includes 5 random integers between 1 to 1000
np.random.randint(1,1000,5)

array([748, 789, 122,   5,  36])

In [29]:
#create 2-d array of order (2,2) which includes random integers between 20 to 60
#size : number of rows and columns
np.random.randint(20,60,size=(2,2))

array([[52, 40],
       [52, 50]])

In [30]:
#create 2d array of order(2,3) which includes random int between 2 to 200
np.random.randint(2,200,size=(2,3))

array([[ 73,  71, 116],
       [174, 100, 128]])

**rand**

In [31]:
#rand-- generates a random values between the  range[0,1]

In [2]:
#generate 10 random numbers between 0 to 1
import numpy as np
np.random.rand(0,1)


array([], shape=(0, 1), dtype=float64)

**randn**

In [3]:
# It is used to generate random numbers from normal distribution within a range[-3,3]

In [4]:
#generate 10 random numbers from normal distribution
np.random.randn(10)

array([-0.36880226, -0.60854013,  0.95366726,  0.2126568 , -0.26204722,
       -0.88496525,  0.45502581,  1.18499863, -0.14262271, -0.45955007])

In [5]:
#create a 2d array of order(5,5) which includes normal disrtibution values
np.random.randn(5,5)

array([[-1.37665122,  1.59830657, -1.05910367, -0.00575785, -0.21098786],
       [ 0.12998827, -1.07023386,  0.19369908, -0.46209304,  0.23400744],
       [-0.15730159, -0.52496714, -0.04706712, -0.23872016, -0.05889496],
       [ 2.22801267, -0.40383661,  0.81450774,  0.15014139, -0.81288406],
       [ 0.76565766, -0.49124368, -0.22820188, -2.54184417, -0.12822518]])

In [12]:
#create 10 random numbers 1 to 10000
arr1=np.random.randint(1,10000,10)
print(arr1)

[7578 9733 4099 8607 2178 8370 1644 1585  743 2267]


In [13]:
#maximum value 
np.max(arr1)

9733

In [15]:
#argmax : Is used to get the index value of maximum value in array
np.argmax(arr1)

1

In [17]:
np.min(arr1)
#argmin is used to get the index value of minimum value in array
np.argmin(arr1)

8

**Indexing**

In [20]:
a=np.arange(20,30)
print(a)

[20 21 22 23 24 25 26 27 28 29]


In [22]:
#fetch 23
a[3]

23

In [23]:
#fetch 23,24,25
a[3:6]

array([23, 24, 25])

In [24]:
# how to reverse an array
a[::-1]

array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20])

**Indexing with 2D array**

In [4]:
#extracctin rows and columns
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
#indexing by giving row and column index
arr[1,1]

5

In [31]:
#fetch first row
arr[[0]]

array([[1, 2, 3]])

In [32]:
#fetch third row
arr[[2]]

array([[7, 8, 9]])

In [35]:
#fetch 1 and 2nd row
#[[]] two braces are imp in fetching multiple rows
arr[[0,1]]

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
#fetch first and third row
arr[[0,2]]

array([[1, 2, 3],
       [7, 8, 9]])

In [6]:
#fetch 4 (it can be fetch using two ways)
arr[1,0]

4

In [9]:
#fetch fist column
arr[:,[0]]

array([[1],
       [4],
       [7]])

In [10]:
#fetch third column
arr[:,[2]]

array([[3],
       [6],
       [9]])

In [12]:
#fetch 1st and second column
arr[:,[0,1]]

array([[1, 2],
       [4, 5],
       [7, 8]])

### Slicing

In [4]:
#slicing 1D array
arr = np.array([10, 20, 30, 40, 50, 60])

print("Original Array:", arr)

# Slicing [start:end] → end is excluded
print("arr[1:4] =", arr[1:4])        # Elements from index 1 to 3
print("arr[:3] =", arr[:3])          # First 3 elements
print("arr[3:] =", arr[3:])          # Elements from index 3 onwards
print("arr[::2] =", arr[::2])        # Every 2nd element


Original Array: [10 20 30 40 50 60]
arr[1:4] = [20 30 40]
arr[:3] = [10 20 30]
arr[3:] = [40 50 60]
arr[::2] = [10 30 50]


In [5]:
#Slicing 2D Array
# Creating a 2D array (matrix)
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Original Matrix:\n", matrix)

# Extracting a single row
print("First Row:", matrix[0])

# Extracting a single column
print("Second Column:", matrix[:, 1])

# Extracting a submatrix
print("Submatrix (first 2 rows, 2 columns):\n", matrix[:2, :2])


Original Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
First Row: [1 2 3]
Second Column: [2 5 8]
Submatrix (first 2 rows, 2 columns):
 [[1 2]
 [4 5]]


In [6]:
# Creating a 1D array
arr = np.arange(1, 13)   # [1, 2, 3, ..., 12]
print("Original Array:", arr)

# Reshape into 3 rows and 4 columns
reshaped = arr.reshape(3, 4)
print("\nReshaped (3x4):\n", reshaped)

# Reshape into 2 rows and 6 columns
reshaped2 = arr.reshape(2, 6)
print("\nReshaped (2x6):\n", reshaped2)


Original Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped (3x4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Reshaped (2x6):
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


### Mathematical Operations on Arrays

In [7]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

print("Addition:", arr1 + arr2)
print("Subtraction:", arr1 - arr2)
print("Multiplication:", arr1 * arr2)
print("Division:", arr1 / arr2)

# Scalar operation
print("Multiply every element by 2:", arr1 * 2)


Addition: [11 22 33 44]
Subtraction: [ 9 18 27 36]
Multiplication: [ 10  40  90 160]
Division: [10. 10. 10. 10.]
Multiply every element by 2: [20 40 60 80]


### Aggregation Functions (sum, mean, std, max, min)

In [ ]:
data = np.array([[2, 4, 6],
                 [8, 10, 12]])

print("Sum of all elements:", np.sum(data))
print("Column-wise Sum:", np.sum(data, axis=0))
print("Row-wise Sum:", np.sum(data, axis=1))

print("\nMean (average):", np.mean(data))
print("Standard Deviation:", np.std(data))
print("Maximum Value:", np.max(data))
print("Minimum Value:", np.min(data))
