In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris=load_iris()

In [4]:
data=sns.load_dataset('iris')

In [5]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [6]:
data.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [7]:
x=data.drop('species',axis=1)
y=iris.target

In [8]:
x

sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [9]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [10]:
## train tset split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)

In [11]:
from sklearn.tree import DecisionTreeClassifier

In [12]:
#model
treemodel=DecisionTreeClassifier(max_depth=2)

In [13]:
treemodel.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=2)

In [14]:
from sklearn import tree
plt.figure(figsize=(15,10))
tree.plot_tree(treemodel,filled=True)

[Text(0.4, 0.8333333333333334, 'x[2] <= 2.45\ngini = 0.664\nsamples = 105\nvalue = [31, 37, 37]'),
 Text(0.2, 0.5, 'gini = 0.0\nsamples = 31\nvalue = [31, 0, 0]'),
 Text(0.30000000000000004, 0.6666666666666667, 'True  '),
 Text(0.6, 0.5, 'x[3] <= 1.75\ngini = 0.5\nsamples = 74\nvalue = [0, 37, 37]'),
 Text(0.5, 0.6666666666666667, '  False'),
 Text(0.4, 0.16666666666666666, 'gini = 0.214\nsamples = 41\nvalue = [0, 36, 5]'),
 Text(0.8, 0.16666666666666666, 'gini = 0.059\nsamples = 33\nvalue = [0, 1, 32]')]

In [15]:
#prediction
y_pred=treemodel.predict(x_test)

In [16]:
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0])

In [17]:
from sklearn.metrics import accuracy_score,classification_report

In [18]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [19]:
## prepuining
parameter={
    'criterion':['gini','entropy','log_loss'],
    'splitter':['best','random'],
    'max_depth':[1,2,3,4,5],
    'max_features':['auto','sqrt','log2']
}


In [20]:
from sklearn.model_selection import GridSearchCV

In [21]:
treemodel=DecisionTreeClassifier()
cv=GridSearchCV(treemodel,param_grid=parameter,cv=5,scoring='accuracy')

In [22]:
cv.fit(x_train,y_train)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_depth': [1, 2, 3, 4, 5],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             scoring='accuracy')

In [23]:
cv.best_params_

{'criterion': 'gini',
 'max_depth': 3,
 'max_features': 'sqrt',
 'splitter': 'best'}

In [24]:
y_pred=cv.predict(x_test)

In [25]:
from sklearn.metrics import accuracy_score,classification_report

In [26]:
score=accuracy_score(y_pred,y_test)

In [27]:
score

0.9777777777777777

In [28]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.95      1.00      0.97        18
           1       1.00      0.93      0.96        14
           2       1.00      1.00      1.00        13

    accuracy                           0.98        45
   macro avg       0.98      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45



#### Random Forest (Bagging Method)

Random Forest = Many Decision Trees + Voting/Averaging

Simple Explanation

* A single decision tree is weak, overfits, and is unstable.
* So Random Forest creates many trees and combines them.

How it works (Step-by-step)

* 1️ Take the original dataset
* 2️ Create multiple bootstrap samples (random samples with replacement)
* 3️ Build one decision tree on each sample
* 4️ At each split, choose random subset of features
* 5️ Final output =
* Classification → Majority vote
* Regression → Average of all trees

#### Why it is better than a single tree?

* Reduces overfitting (major advantage)
* Reduces variance
* More accurate and stable
* Works well even with missing values
* Handles thousands of features
* Less sensitive to noise

In [33]:
# RandomForset implementation
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=100,
    max_depth=5,
    random_state=42
)

rf.fit(x_train, y_train)
r_pred=cv.predict(x_test)

print("Random Forest Accuracy:", accuracy_score(y_test, r_pred))


Random Forest Accuracy: 0.9777777777777777


#### Gradient Boosting (Boosting Method)

Gradient Boosting = Build trees sequentially, each tree fixes mistakes of the previous one.

Simple Explanation
* Unlike Random Forest (parallel), Gradient Boosting builds trees one after another.
* Each new tree focuses on the errors (residuals) made by previous trees.

How it works

* 1️ Start with a simple model (weak learner)
* 2️ Predict output — errors happen
* 3️ Build the next tree to correct those errors
* 4️ Repeat…
* 5️ Final model = sum of all weak trees

Example (simple idea)

* Tree 1 → predicts 70% correctly
* Tree 2 → tries to fix mistakes of Tree 1
* Tree 3 → fixes mistakes of Tree 2
* Final accuracy becomes very high

Why it's powerful?

* Low bias, low error
* Works very well on structured/tabular data
* Best for small/medium datasets

Disadvantages:

* Slow training
* Can overfit if not tuned properly
* Sensitive to outliers

In [34]:
from sklearn.ensemble import GradientBoostingClassifier

gb = GradientBoostingClassifier(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=3,
    random_state=42
)

gb.fit(x_train, y_train)
gb_pred = gb.predict(x_test)

print("Gradient Boosting Accuracy:", accuracy_score(y_test, gb_pred))


Gradient Boosting Accuracy: 1.0


#### XGBoost (Extreme Gradient Boosting)

Why XGBoost is better?

XGBoost adds four big improvements:

* 1. Regularization (L1 & L2)
* Controls overfitting
* (This is why XGBoost performs better than plain GradientBoosting)

* 2. Parallel processing
* Trains much faster

* 3. Tree pruning
* Uses “max_depth” + “learning_rate” + “gamma” to avoid huge trees

* 4. Handles missing values automatically
     
###### How XGBoost works (intuition)

* Same boosting idea (tree-by-tree)
BUT optimized with:
* Regularization
* Shrinkage
* Weighted quantile histogram
* Handling sparse data
* Efficient memory usage
* So it becomes fast + powerful.

In [38]:
from xgboost import XGBClassifier

xgb = XGBClassifier(
    n_estimators=150,
    learning_rate=0.1,
    max_depth=4,
    eval_metric='logloss'
)

xgb.fit(x_train, y_train)
xgb_pred = xgb.predict(x_test)

print("XGBoost Accuracy:", accuracy_score(y_test, xgb_pred))


XGBoost Accuracy: 1.0
